# Generated by Django 6.0.2 on 2026-02-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_treinador_p1_treinador_p2_treinador_p3_treinador_p4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='fraqueza',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
