# Generated by Django 6.0.2 on 2026-02-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_pokemon_fraqueza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fraquezas', models.TextField()),
                ('efetivos', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='fraqueza',
            new_name='efetivos',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='fraquezas',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
