# Generated by Django 6.0.2 on 2026-02-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_tipo_rename_fraqueza_pokemon_efetivos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='resistencia',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
