# Generated by Django 6.0.2 on 2026-02-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_tipo_resistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='resistencia',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
