# Generated by Django 6.0.2 on 2026-02-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_pokemon_resistencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='resistencia',
            new_name='imunidade',
        ),
    ]
