# Generated by Django 6.0.2 on 2026-02-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_rename_resistencia_tipo_imunidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='resistencia',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
